### ISSUE TITLE
Testris should capture exceptions when unable to run learntris.

### ISSUE THREAD

**Issue by tangentstorm** [LearnProgramming/learntris#16]
Basically, if anything happens other than a successful run of the program (where it finishes and returns error code 0), then we should display a helpful message to the user.

As it stands, a failure to launch causes a traceback to be thrown, which isn't useful for anyone who doesn't happen to be learning python. :) Exceptions should be trapped.

**Comment by ThatBob9001** [comment]
I totally agree with this, seeing as this is happening to me. I created a blank file called "learntris", just as it first instructs, but when I run it all I get is this: http://pastebin.com/Z6SEpuHB

**Comment by tangentstorm** [comment]
Thanks. I added some better error messages.

You probably just need to run `chmod +x` on your implementation.
