### ISSUE TITLE
Test2 does not pass even with correct code

### ISSUE THREAD

**Issue by mbakthav** [LearnProgramming/learntris#35]
I was playing around with learntris to learn as well as to contribute to this effort. I have a program which prints out the '.' in the correct format. I verified this from the command line. The correct code is here
http://pastebin.com/jEBVC987
But test2 does not pass

**Comment by tangentstorm** [comment]
Thanks for trying learntris! :)

Your implementation is meant to read the commands from standard input, not the command line. The idea is you should be able to type the commands manually yourself to test things interactively. And also, it's a game, so it has to be a loop where the player is sending input dynamically in response to the output.

Make sense?

**Comment by mbakthav** [comment]
yes. indeed.  This one passed. http://pastebin.com/mh2SDycj
