### ISSUE TITLE
Test 8 stdout error

### ISSUE THREAD

**Issue by LelouchVlBritannia** [LearnProgramming/learntris#44]
```
Traceback (most recent call last):
  File "testris.py", line 163, in main
    try: run_tests(cmdline, use_shell)
  File "testris.py", line 135, in run_tests
    run_test(program, opcodes)
  File "testris.py", line 119, in run_test
    program.stdout.read().decode('utf-8').split("\n")]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 32: invalid
 start byte

Oh no! Testris encountered an unexpected problem while
attempting to run your program. Please report the above
traceback in the issue tracker, so that we can help you
with the problem and provide a better error message in
the future.
```

https://github.com/LelouchVlBritannia/learntris - my code is in there ( its a mess)
MinGW/MSYS -- GCC 4.8.1
Python 3.4

Most likely I am doing something really weird but just reporting because it said to report it.

**Comment by tangentstorm** [comment]
Hrm. Yes, there's no reason that testris needs the output to be utf-8, so this is a bug.

But, there's also no reason your code should be emitting character 0xff...

**Comment by tangentstorm** [comment]
Looks like you got it worked out on your end. Thanks for the bug report. :)

**Comment by LelouchVlBritannia** [comment]
No problem! and if you would like to see the code then I had pushed my code before I edited it so you should be able to reproduce the error.
