### ISSUE TITLE
Trouble getting started with Java

### ISSUE THREAD

**Issue by JuanUp** [LearnProgramming/learntris#47]
I read through the RUNNING PROGRAMS OTHER THAN EXECUTABLE BINARIES section and attempted to apply it to Java, but when I try this i keep getting an error that reads:

File Not Found: C:\windows\system32\java.exe

but it's there. I know because if I run the following in CMD, it works as it should (blank output).
C:\windows\system32\java.exe learntris

**Comment by tangentstorm** [comment]
try this:

    testris.py --shell "c:\windows\system32\java.exe Learntris"

Also, you might want to think about using the `java.exe` that comes with the jdk you're using, rather than the windows one.

**Comment by JuanUp** [comment]
Thank you very much @tangentstorm You hit the nail on the head with the jdk suggestion. I wasn't even aware there existed 2 versions of java.exe on my computer. On to the next phase...

**Comment by tangentstorm** [comment]
NP. Good Luck!
