### ISSUE TITLE
unknown error with test 9

### ISSUE THREAD

**Issue by ashoknailwal** [LearnProgramming/learntris#49]
Traceback (most recent call last):
  File "testris.py", line 165, in main
    run_tests(cmdline, use_shell)
  File "testris.py", line 135, in run_tests
    run_test(program, opcodes)
  File "testris.py", line 119, in run_test
    program.stdout.read().decode('utf-8').split("\n")]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 18: invalid continuation byte
--------------------------------------------------
Oh no! Testris encountered an unexpected problem while
attempting to run your program. Please report the above
traceback in the issue tracker, so that we can help you
with the problem and provide a better error message in
the future.

May be something is wrong with my code .
But it said to report it so here I am.
Here is my code :-https://github.com/ashoknailwal/learntris

**Comment by darkf** [comment]
@ashoknailwal Your program is sending garbage output on the `t` command:

	$ ./a.exe
	O
	t
	▌ F w ╝
	I w    
	  $
	á ² (
	q

This probably should be a friendlier error, but you should always manually inspect the output when this happens.
