### ISSUE TITLE
Add graphcial learntris frontend

### ISSUE THREAD

**Issue by darkf** [LearnProgramming/learntris#50]
Being able to graphically play your game would be a great motivation.

This would be best done in either standard Python (i.e. with Tkinter), or as a Web app (preferably using the Python standard library again, or at least `bottle.py` so that we could drop it in.)

A Web app could use WebSockets to communicate, and Canvas or SVG to draw.

If anyone wants to attempt this (feel free!), don't hesitate to drop by #learnprogramming (see the README for a link) and mention it. We wouldn't mind to guiding you.

**Comment by tangentstorm** [comment]
See  https://github.com/tangentcode/lt-shell
