### ISSUE TITLE
Issue with trying to run "python testris.py learntris.py"

### ISSUE THREAD

**Issue by aaronfox** [LearnProgramming/learntris#53]
When I use C:\Users\aaron\learntris>python testris.py 
I get the typical message of: "Testris is the test runner for testris... File not found: ./learntris"

Now, this is the message I get whenever I try to run: C:\Users\aaron\learntris> python testris.py learntris.py
I think that this should work (I'm using windows cmd.exe and python is in my path).

Any assistance would be wonderful!

---

Traceback (most recent call last):
  File "testris.py", line 165, in main
    run_tests(cmdline, use_shell)
  File "testris.py", line 131, in run_tests
    program = spawn(program_args, use_shell)
  File "testris.py", line 81, in spawn
    stdout=subprocess.PIPE)
  File "C:\Program Files (x86)\Python35-32\lib\subprocess.py", line 947, in **init**
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

---

Oh no! Testris encountered an unexpected problem while
attempting to run your program. Please report the above
traceback in the issue tracker, so that we can help you
with the problem and provide a better error message in
the future.

  https://github.com/LearnProgramming/learntris/issues

**Comment by darkf** [comment]
Try `python testris.py python learntris.py`

**Comment by bigmanstan** [comment]
Try c:\learntris>  c:\python27\python.exe testris.py c:\python27\python.exe learntris.py
   change the directory accordingly

**Comment by bigmanstan** [comment]
Try python testris.py python learntris.py`cdgg` **dgfdfgdfg**
