### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Nasrin-Shiraly** [LearnProgramming/learntris#56]
Running Testris on windows 10, python3.7
Contents of my learntris.py:
import sys
sys.stdin.readline()
the error I'm seeing:

Traceback (most recent call last):
  File "testris.py", line 168, in main
    run_tests(cmdline, use_shell)
  File "testris.py", line 134, in run_tests
    program = spawn(program_args, use_shell)
  File "testris.py", line 84, in spawn
    stdout=subprocess.PIPE)
  File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Oh no! Testris encountered an unexpected problem while
attempting to run your program. Please report the above
traceback in the issue tracker, so that we can help you
with the problem and provide a better error message in
the future.

  https://github.com/LearnProgramming/learntris/issues

**Comment by darkf** [comment]
You might need to run it like `python testris.py --shell python learntris.py`

See if that helps.

**Comment by Nasrin-Shiraly** [comment]
It did. Can we please have that in the documentation? Thank you.

**Comment by darkf** [comment]
Glad it worked. It's indeed a bit hidden in the [Getting Set Up](https://github.com/LearnProgramming/learntris/wiki/Getting-Set-Up) wiki page, and even then it's not *too* clear. It should be mentioned more prominently IMO.

Since this is fixed, I'll close the issue. Cheers.
